#!/bin/sh

### BEGIN INIT INFO
# Provides:          epv
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Erlang Photo Viewer
# Description:       EPV is lightweight and minimalistic Web-gallery
#                    for your photographs and videos.
### END INIT INFO

# Author: Aleksey Morarash <aleksey.morarash@gmail.com>

PATH=/sbin:/bin:/usr/bin
DESC="Erlang Photo Viewer"
NAME=epv
DAEMON=/usr/bin/${NAME}-wrapper
PIDFILE=/var/lib/$NAME/pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Generate command line for the daemon
DAEMON_ARGS="$MEDIA_PATH $CACHE_PATH"
[ -n "$LANGUAGE" ] && DAEMON_ARGS="-l $LANGUAGE $DAEMON_ARGS"
[ -n "$BIND_ADDR" ] && DAEMON_ARGS="-i $BIND_ADDR $DAEMON_ARGS"
[ -n "$BIND_PORT" ] && DAEMON_ARGS="-p $BIND_PORT $DAEMON_ARGS"
[ "$SHOW_TAGS" = "yes" -o "$SHOW_TAGS" = "1" -o "$SHOW_TAGS" = "true" ] || \
    DAEMON_ARGS="--no-tags $DAEMON_ARGS"
[ -n "$LOG_PATH" ] && DAEMON_ARGS="--log $LOG_PATH $DAEMON_ARGS"
[ -n "$LOGLEVEL" ] && DAEMON_ARGS="-v $LOGLEVEL $DAEMON_ARGS"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start() {
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    do_status && return 1
    start-stop-daemon --quiet --start --background --make-pidfile \
        --pidfile $PIDFILE --user $NAME --chuid $NAME \
        --exec $DAEMON -- $DAEMON_ARGS || return 2
}

#
# Function that stops the daemon/service
#
do_stop() {
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
        --pidfile $PIDFILE --user $NAME
    RETVAL="$?"
    [ "$RETVAL" = 2 ] && return 2
    rm -f $PIDFILE
    return "$RETVAL"
}

#
# Function that checks the daemon/service status
#
do_status(){
    # Return
    #   0 if program is running.
    #   1 if program is not running and the pid file exists.
    #   3 if program is not running.
    #   4 unable to determine program status.
    start-stop-daemon --quiet --status --pidfile $PIDFILE --user $NAME
}

case "$1" in
    start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        do_status
        RETVAL="$?"
        if [ "$VERBOSE" != no ]; then
            case "$RETVAL" in
                0) log_success_msg "$DESC $NAME is running" ;;
                1|3) log_failure_msg "$DESC $NAME is not running" ;;
                4) log_failure_msg "$DESC $NAME: failed to get status" ;;
            esac
        fi
        exit $RETVAL
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;; # Old process is still running
                    *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac

:
